from typing import AsyncGenerator, List, Dict, Any
import json

async def generate_response_stream(
    query: str, 
    context_chunks: List[Dict[str, Any]],
    system_instruction: str = None
) -> AsyncGenerator[str, None]:
    
    if not context_chunks:
        yield "### No Results Found\n\n"
        yield "I'm sorry, I couldn't find any relevant information in the uploaded documents to answer your question. Please try rephrasing or asking something else."
        return

    yield "### Extractive Source Insights\n\n"
    yield "*I have analyzed your documentation and identified the following excerpts that directly address your query:*\n\n---\n\n"
    
    for i, chunk in enumerate(context_chunks, 1):
        title = chunk['meta'].get('docTitle', 'Unknown Document')
        text = chunk['text']
        
        yield f"#### Source {i}: {title}\n\n"
        yield f"> {text}\n\n"
        
        if i < len(context_chunks):
            yield "\n---\n\n"
            
    yield "\n*Note: This response was generated by extracting top matching chunks directly from your documents.*"
